config/routes.rb
Rails.application.routes.draw do
  resources :actors
  resources :characters
  resources :movies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :characters
  has_many :movies, through: :characters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :movie, optional: true
  belongs_to :actor, optional: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :characters
  has_many :actors, through: :characters
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :select_actor, only: [:show, :edit, :update, :destroy]

  def index
    @actors = Actor.all
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def select_actor
    @actor = Actor.find(params[:id])
  end

  private

  def actor_params
    params.require(:actor).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :select_character, only: [:show, :edit, :update, :destroy]

  def index
    @characters = Character.all
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def select_character
    @character = Character.find(params[:id])
  end

  private

  def character_params
    params.require(:character).permit(:name, :movie_id, :actor_id)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :select_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.all
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def select_movie
    @movie = Movie.find(params[:id])
  end

  private

  def movie_params
    params.require(:movie).permit(:title)
  end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/actors/edit.html.erb
<h1>Actors#edit</h1>
<p>Find me in app/views/actors/edit.html.erb</p>

app/views/actors/index.html.erb
<h1>Actors</h1>
<ul>
  <% @actors.each do |actor| %>
  <li><%= link_to actor.name, actor_path(actor) %></li>
  <% end %>
</ul>

app/views/actors/new.html.erb
<h1>Actors#new</h1>
<p>Find me in app/views/actors/new.html.erb</p>

app/views/actors/show.html.erb
<h1><%= @actor.name %></h1>

<h3>Movie:</h3>
<p>
  <% @actor.characters.each do |character| %>
  <%= link_to character.movie.title, character.movie %>
  <% end %>
</p>

<h3>Character:</h3>
<p>
  <% @actor.characters.each do |character| %>
  <%= link_to character.name, character %>
  <% end %>
</p>

app/views/characters/edit.html.erb
<h1>Characters#edit</h1>
<p>Find me in app/views/characters/edit.html.erb</p>

app/views/characters/index.html.erb
<h1>Characters</h1>
<ul>
  <% @characters.each do |character| %>
  <li><%= link_to character.name, character_path(character) %></li>
  <% end %>
</ul>

app/views/characters/new.html.erb
<h1>Characters#new</h1>
<p>Find me in app/views/characters/new.html.erb</p>

app/views/characters/show.html.erb
<h1><%= @character.name %></h1>

<h3> Movie: </h3>
<p><%= link_to @character.movie.title, movie_path %></p><br>

<h3> Actor: </h3>
<p><%= link_to @character.actor.name, actor_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>
<p>Find me in app/views/movies/edit.html.erb</p>

app/views/movies/index.html.erb
<h1>Movies</h1>
<ul>
  <% @movies.each do |movie| %>
  <li><%= link_to movie.title, movie_path(movie) %></li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<h3>Character:</h3>
<p>
  <% @movie.characters.each do |character| %>
  <%= link_to character.name, character %>
  <% end %>
</p>

<h3>Actor:</h3>
<p>
  <% @movie.characters.each do |character| %>
  <%= link_to character.actor.name, character.actor %>
  <% end %>
</p>